### ISSUE TITLE
Windows node pools are not supported on kubenet cluster

### ISSUE THREAD

**Issue by osamabinsaleem** [LM-Development/aks-sample#31]
From the readme file on [this page](https://github.com/LM-Development/aks-sample/blob/main/Samples/PublicSamples/RecordingBot/docs/deploy/aks.md): 
```
You will need a Windows VM Scale Set with more than 2 vCPU. If you deploy the bot to a VM that does not, the bot will not run. Standard_DS3_v2 should be enough to get the bot running.
```

The docs say that a Windows VM should be created. When you go to create a node pool, windows is disabled by default as shown in the image. 

<img width="1466" alt="Screenshot 2024-03-05 at 3 27 41 PM" src="https://github.com/LM-Development/aks-sample/assets/37154675/44d483ab-5002-4f4e-ac5d-a9ae3cd55ecb">

**Comment by 1fabi0** [comment]
Hey, you need a Systemnodepool first which is requered to be Linux, after that you can add a windows nodepool to the AKS see [this](https://learn.microsoft.com/en-us/azure/aks/learn/quick-windows-container-deploy-cli?tabs=add-windows-node-pool) for reference
