### ISSUE TITLE
Docker image build errors

### ISSUE THREAD

**Issue by osamabinsaleem** [LM-Development/aks-sample#51]
I'm trying to build the docker image using this command: 
```
docker build `
>>     --build-arg CallSignalingPort=<CALL_SIGNALING_PORT> `
>>     --build-arg CallSignalingPort2=<CALL_SIGNALING_PORT+1> `
>>     --build-arg InstanceInternalPort=<INSTANT_INTERNAL_PORT> `
>>     -f ./build/Dockerfile . `
>>     -t latest
```

I'm getting this error:
<img width="831" alt="Screenshot 2024-03-14 at 6 04 36 PM" src="https://github.com/LM-Development/aks-sample/assets/37154675/afcb6bd2-0cf8-46a3-9653-24f4eaec0a85">

**Comment by 1fabi0** [comment]
Make sure the system you build the image on is a windows x64 System, seems like you're platform is not windows/x64 I don't have any other explenation for this issue out of the blue, https://hub.docker.com/_/microsoft-windows-server

**Comment by osamabinsaleem** [comment]
I'm gonna try this on a new machine now but I'm pretty sure the issue that I got was on a i3 intel based laptop with windows 10 installed on it.

**Comment by 1fabi0** [comment]
@osamabinsaleem Hi, I just merged a tutorial, how to deploy the applciation to a new AKS cluster, there we don't use the local machine to build the docker image, maybe check out [the tutorial](https://github.com/LM-Development/aks-sample/blob/main/Samples/PublicSamples/RecordingBot/docs/tutorials/deploy-tutorial.md) to deploy the sample

**Comment by 1fabi0** [comment]
Hi @osamabinsaleem To create this tutorial I used a Windows 11 machine but it should work fine on a windows 10 machine(maybe this also was your docker building problem but in the tutorial we build the docker image in the ACR). If you experience any problems with windows 10 please mention them here maybe we can make the tutorial windows 10 safe.

**Comment by osamabinsaleem** [comment]
Thanks @1fabi0 I've upgrated to windows 11.
