### ISSUE TITLE
Resource cleanup for cost savings 

### ISSUE THREAD

**Issue by osamabinsaleem** [LM-Development/aks-sample#58]
The updated [instructions](https://github.com/LM-Development/aks-sample/blob/main/Samples/PublicSamples/RecordingBot/docs/tutorials/deploy-tutorial.md) to build and deploy the bot is missing the cleanup section. 

Can you please add a section containing instructions to cleanup all the resources permannetly as well to stop them when they're not in use for cost savings?

**Comment by 1fabi0** [comment]
Thank you @osamabinsaleem
You can delete the resource groups in your azure subscription to cleanup costwise, to completly remove everything you also have to delete the app registration.

 I will add this to our todos, thanks

**Comment by InDieTasten** [comment]
Closed by #66
