### ISSUE TITLE
Feature Request: Custom FQDN for cluster

### ISSUE THREAD

**Issue by InDieTasten** [LM-Development/aks-sample#60]
It would be interesting to have docs on how to deploy with a custom domain.

**Comment by InDieTasten** [comment]
This would also benefit issues, such as rate-limiting for commonly used azure cloudapps domains for let's encrypt. See #59 for example.

**Comment by InDieTasten** [comment]
In general, it doesn't take much to utilize a custom domain.

1. Have a custom domain with a CNAME towards the built-in domain of the loadbalancer IP (xxxx.{region}.cloudapp.azure.com)
2. During deployment of the chart, provide the custom domain for the FQDN. (which is the parameter `hostName` I believe)
3. Done?

**Comment by 1fabi0** [comment]
How to describe a Setup for multiple DNS providers hundreds of dns providers have quoite a lot of ways to setup DNS entrys. This makes it quite difficult for starters, either they need the same DNS provider as in an example or they already need to know how to do the setup.

**Comment by InDieTasten** [comment]
@1fabi0 I don't think we need to explain how to setup the CNAME record. But the steps 1-3 I described could be part of the docs. It just needs to be verified, that these steps are all that is necessary to get a custom domain to work. Maybe I forgot something.

**Comment by InDieTasten** [comment]
@osamabinsaleem if you go this route, please let is know if it works and if there were any steps missing. Then we would include these in the docs in the future :)
